use_frameworks!

platform :ios, '8.0'

target 'LJUIKit_Example' do
  pod 'LJUIKit', :path => '../'
  pod 'Masonry'
  pod 'MaryPopin'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'MJExtension'

  target 'LJUIKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
